name: make-package
version: '1.2.0'
synopsis: Make a cabalized package
description: Create a cabalized haskell project
category: Development, Utils
author: Philipp Balzarek
maintainer: p.balzarek@googlemail.com
copyright:
  - Chris Done
  - Philipp Balzarek
license: BSD3
homepage: https://github.com/Philonous/make-package
bug-reports: https://github.com/Philonous/make-package/issues/
extra-source-files:
  - make-package.conf
dependencies:
  - base >=4 && <5
  - aeson
  - async >=2.0
  - bytestring >=0.10
  - configurator >=0.2
  - containers >=0.5
  - directory >=1.2
  - exceptions
  - filepath >=1.3
  - github >=0.11
  - haskeline >=0.7
  - lens >=3.10
  - lens-datetime >=0.2
  - microstache
  - mtl >=2.1
  - process >=1.1
  - text >=0.10
  - time >=1.4
  - unix-compat
executables:
  make-package:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
data-files:
  - files/**/*
